export const CLOTHES = [
  {
    product: "Jeans",
    color: "blue",
    gender: "male",
    size: "s",
    price: 1199,
  },
  {
    product: "shirt",
    color: "pink",
    gender: "female",
    size: "m",
    price: 699,
  },
  {
    product: "skirt",
    color: "yellow",
    gender: "female",
    size: "s",
    price: 999,
  },
  {
    product: "t-shirt",
    color: "red",
    gender: "male",
    size: "l",
    price: 599,
  },
  {
    product: "formal pants",
    color: "blue",
    gender: "male",
    size: "m",
    price: 1499,
  },
  {
    product: "cargo jeans",
    color: "khaki",
    gender: "male",
    size: "l",
    price: 1999,
  },
  {
    product: "hoddie",
    color: "white",
    gender: "male",
    size: "m",
    price: 799,
  },
  {
    product: "shorts",
    color: "black",
    gender: "female",
    size: "m",
    price: 599,
  },
  {
    product: "saree",
    color: "red",
    gender: "female",
    size: "m",
    price: 7999,
  },
  {
    product: "shirt",
    color: "blue",
    gender: "female",
    size: "m",
    price: 759,
  },
];
